apiVersion: storage.k8s.io/v1
kind: CSIDriver

metadata:
  name: efs.csi.aws.com

spec:
  attachRequired: false

---

apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: aceitchecripto-psql-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"

provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-09f612b6c47a21a07
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/dynamic_provisioning" # optional

---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: aceitchecripto-psql-pvc

spec:
  storageClassName: aceitchecripto-psql-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi