apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: nginx-ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aceitchecripto-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-ingress-class
  rules:
    - host: aceitchecripto.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aceitchecripto-backend-service
                port:
                  name: http
          - path: /adminer
            pathType: Prefix
            backend:
              service:
                name: aceitchecripto-adminer-service
                port:
                  name: http