apiVersion: storage.k8s.io/v1
kind: CSIDriver

metadata:
  name: efs.csi.aws.com

spec:
  attachRequired: false

---

apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: aceitchecripto-psql-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"

provisioner: efs.csi.aws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: aceitchecripto-psql-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aceitchecripto-psql-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f25b40d52a5e06b7

---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: aceitchecripto-psql-pvc

spec:
  storageClassName: aceitchecripto-psql-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi